language: php
php:
  - 5.5
  - 5.6
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install
  - npm install --global gulp
  - npm install
  - gulp
  - mysql -e 'create database kc3_main;'
  - php artisan migrate
